export const PROFILE_ROUTE = '/profile'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ROOMS_ROUTE = '/'
export const ROOM_ROUTE = '/room'
export const BOOKING_DETAIL_ROUTE = '/booking'